# Generated by Django 3.2.25 on 2024-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=1, upload_to='photos'),
            preserve_default=False,
        ),
    ]
